trigger:
  - main
  - dev

pool:
  vmImage: ubuntu-latest

steps:
- script: |
    echo $(GithubToken) | gh auth login --with-token
    gh auth setup-git
  displayName: "Configure gh cli"
  env:
    GHTOKEN: $(GithubToken)

- script: |
    git remote set-url origin https://$AZTOKEN@dev.azure.com/ashenhasanka12/GroupProject/_git/GroupProject
    git fetch
    git pull
    git remote add github https://github.com/ashen92/GroupProject.git
    git checkout main
    git push -f github main
    git checkout dev
    git push -f github dev
  displayName: "Push to GitHub"
  env:
    AZTOKEN: $(AzureDevOpsToken)