trigger:
  - main
  - dev

pool:
  vmImage: ubuntu-latest

steps:
  - script: |
      echo $(GithubToken) | gh auth login --with-token
      gh auth setup-git
    displayName: "Configure gh cli"
    env:
      GHTOKEN: $(GithubToken)

  - script: |
      git config --global http.postBuffer 524288000
      git remote set-url origin https://$AZTOKEN@dev.azure.com/ashenhasanka12/GroupProject/_git/GroupProject
      git fetch origin
      git remote add github https://github.com/ashen92/GroupProject.git
      git push --mirror github
    displayName: "Push to GitHub"
    env:
      AZTOKEN: $(AzureDevOpsToken)
