version: "3"
services:
  web:
    image: ashensandaruwan/groupproject
    environment:
      - IS_PRODUCTION=1
      - DB_HOST=db
      - DB_DATABASE=pdc
      - DB_USERNAME=root
      - DB_PASSWORD=root
    ports:
      - "8080:80"
    depends_on:
      - db

  db:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=pdc
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
