services:

    # Services
    twig.loader:
        class: Twig\Loader\FilesystemLoader
        arguments: ["../templates"]

    twig:
        class: Twig\Environment
        arguments:
            - "@twig.loader"
            # - cache: "../cache/twig"

    database.connection:
        class: App\Services\MySQLConnection
        arguments:
            $host: "localhost"
            $db: "pdc"
            $user: "root"
            $password: "root"

    authentication.database:
        class: App\Services\DBAuthenticationService
        arguments: ["@database.connection"]

    # DBContext
    repository.user:
        class: App\Models\UserRepository
        arguments: ["@database.connection"]


    # Controllers
    App\Controllers\SigninController:
        class: App\Controllers\SigninController
        arguments: ["@twig"]

    App\Controllers\HomeController:
        class: App\Controllers\HomeController
        arguments: ["@twig"]

    App\Controllers\AuthenticationController:
        class: App\Controllers\AuthenticationController
        arguments: ["@authentication.database"]
